### ISSUE TITLE
Process encrypted files, in particular images

### ISSUE THREAD

**Issue by arthurlutz** [8go/matrix-commander#1]
First of, kudos for a really easy to setup command line client for matrix. This opens a bunch of possibilities ! 

I'd like to be able to archive photos that are send in a room and matrix-commander seems a good fit for this whist keeping it simple. 

```
matrix-commander.py --listen tail --tail 4 --listen-self
Message received for room octoprint_encrypted [!xxx:matrix.org] | sender Arthur [@xxx:matrix.org] | 2020-09-19 17:02:34 | Received encrypted image: photo.png [https://matrix.org/_matrix/media/r0/download/matrix.org/abcdefg12345]
wget https://matrix.org/_matrix/media/r0/download/matrix.org/abcdefg12345
[snip]
file abcdefg12345
abcdefg12345: data
```

Obviously (and that's good news actually) the file is encryted. 

Any chance of getting the file unencrypted though matrix-nio ?

**Comment by 8go** [comment]
Hi @arthurlutz

Thanks for using `matrix-commander`.

Technically that seems possible. The client always just gets informed that there is a photo on the server. So, by default the encrypted photo always resides on the server and is never pushed to the client. But the `matrix-commander` has a key to it (if `matrix-commander` is verified properly). So, `matrix-commander` in an independent second step could get the photo, i.e. issue a `pull` so to speak.

At the time being, I am focusing on other priorities/projects. But I leave your issue open as a reminder for a possible future `matrix-commander` feature.

If you or someone else wants to provide a PR, please feel free to do so.

Thanks for the suggestion

**Comment by 8go** [comment]
Hi @arthurlutz

Automatic media download and decryption is now implemented.
Download new version. 
Try it and let me know how it goes.

**Comment by 8go** [comment]
Closing the issue now. If there is any feedback, @arthurlutz, let me know here.
