### ISSUE TITLE
Client or credentials not set. Skipping action.

### ISSUE THREAD

**Issue by guhuawuli** [8go/matrix-commander#101]
after installing [matrix-commander] successfully，I use the following command:
matrix-commander --login password

after answering all the questions that popped up

terminal tells me:
INFO: matrix-commander: Aborting due to user request.
ERROR: matrix-commander: Client or credentials not set. Skipping action.
INFO: matrix-commander: 1 error and 0 warnings occurred.

what's the problem? How to solve it?

by the way
os:ubuntu
python:3.810
I installed matrix-commander directly in my docker container which I built by myself

**Comment by 8go** [comment]
Add `--debug` to see more details.
