### ISSUE TITLE
Enhancement: Create DM rooms with users.

### ISSUE THREAD

**Issue by murlock1000** [8go/matrix-commander#107]
Currently, In order to send a DM to a user we first have to create a room with an alias, then invite the user to the room using the newly created room id/alias. When creating such a room, it is not explicitly created as a DM room - does not have the `private` visibility set, so it appears in the `Rooms` section and not `People` in chat applications such as Element. 

Proposal:

Have a separate command to create DM rooms with the provided users, which would invite the user during room creation.
These rooms can also have the alias/name/topic specified as well.

**Comment by 8go** [comment]
Thanks :clap: for the PR @murlock1000 .  Released on PyPi as version v3.5.25.
