### ISSUE TITLE
Bug: SSO login browser launch broken on some distros

### ISSUE THREAD

**Issue by weeksco** [8go/matrix-commander#115]
Great tool, just one small issue for me on first run: 

SSO login fails with "E231: Browser could not be launched" on Manjaro Sway because x-www-browser does not exist. 

I could work around this with a symlink in my path e.g. "ln -s /usr/bin/chromium .local/bin/x-www-browser" 

Maybe xdg-open could be used instead? 

Thanks and keep up the great work

**Comment by 8go** [comment]
@weeksco  Which implementation of `xdg-open` do you recommend?

I currently use `https://pypi.org/project/pyxdg/` but that does NOT have `open`.

There is an `https://pypi.org/project/pyxdg-open/` but it is 8 years old. Also this looks like an executable, not a library.

**Comment by 8go** [comment]
Current code is:

```
            # launch web-browser
            if sys.platform.startswith("darwin"):
                cmd = [shutil.which("open")]
            elif sys.platform.startswith("win"):
                cmd = ["start"]
            else:
                cmd = [shutil.which("x-www-browser")]
```

**Comment by 8go** [comment]
See new version, it tries `xdg-open` first, if that fails as fallback it tries `x-www-browser`.

@weeksco  Please report back if that works for you now.

**Comment by weeksco** [comment]
Perfect! Many thanks
