### ISSUE TITLE
Enhancement: Show invites, Accept invites

### ISSUE THREAD

**Issue by u9000-Nine** [8go/matrix-commander#118]
Is there a way to automatically accept invites, or the recieve invite events with something like the --listen option?

**Comment by ga-it** [comment]
Did you find an answer?

Critical issue for me!

**Comment by u9000-Nine** [comment]
You could use the `-e`/`--event` option, which allows you to use the matrix client–server API. Ideally though, a way to accept invites should be implemented, because if you have to do everything through the API, then it’s not really a client.

**Comment by ga-it** [comment]
In my case - invite after whatsappbot pm request - I can actually accept the invite via --room-join

My issue is actually getting the room id of the invite / listing invites

**Comment by v1-valux** [comment]
I would also like to find a solution for that..
As a "chat-bot" feature, this would be very useful.

any example how to solve it via API?
or a quick way to implement some sort of `join(room_id)` option into the commander script?

**Comment by 8go** [comment]
See version 7.1.0.
