### ISSUE TITLE
Pipe not working?

### ISSUE THREAD

**Issue by koehn** [8go/matrix-commander#120]
When I run using `-m` it works:
```
$ matrix-commander -m test
2023-02-11 13:58:19,805:     INFO: matrix-commander: This message was sent: "test" to room “foo" as event “bar”.
```
When I run using a pipe nothing happens:
```
$ echo test | matrix-commander
$
```

What am I doing wrong?

**Comment by 8go** [comment]
There was some community discussion in the past and this was purposefully disabled. 

The suggested way of doing it: `echo test | matrix-commander -m -`
