### ISSUE TITLE
UNKNOWN_PICKLE_VERSION on clean install on Debian 

### ISSUE THREAD

**Issue by koehn** [8go/matrix-commander#122]
I’m trying to use matrix-commander in a Docker image on Debian. Dockerfile:

```
FROM debian:latest

RUN apt-get update && apt-get install -qqy python libolm-dev pip file zlib1g-dev 

RUN pip3 install --upgrade pip
RUN pip3 install matrix-commander
```

When I launch a container with credentials and store mapped in a volume and run `matrix-commander --devices` I get:
```
2023-03-04 15:57:28,145:    ERROR: matrix-commander: E248: The program matrix-commander.py failed. Sorry.
2023-03-04 15:57:28,145:    ERROR: matrix-commander: UNKNOWN_PICKLE_VERSION
2023-03-04 15:57:28,145:     INFO: matrix-commander: 2 errors and 0 warnings occurred.
```

It looks like the appropriate versions of pickle are installed (at least they match the versions supported by the `matrixcommander/matrix-commander` image:
```
# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> pickle.compatible_formats
['1.0', '1.1', '1.2', '1.3', '2.0', '3.0', '4.0', '5.0']
```

**Comment by koehn** [comment]
Strangely, creating new credentials allows me to login fine. The credentials I made with the `matrixcommander/matrix-commander` image and subsequently mapped into my new image didn’t work. AFAICT, the only difference between the images is that one is built upon redhat and the other on Debian. Why would the credentials/store not be compatible on the same hardware?

**Comment by 8go** [comment]
Thank you @koehn for posting this issue and also for "solving" the issue. 

I am not sure what is behind this, `matrix-commander` certainly is not distinguishing the platforms; it must be some lower level dependency. 

Also I am quite certain it is not the credentials file. According to your description, it must be the `store` directory files.
