### ISSUE TITLE
Feature request/PR proposal: Support for emojis in messages

### ISSUE THREAD

**Issue by jonathandmoore** [8go/matrix-commander#130]
Emoji short codes (e.g. `:collision:`) in messages do not seem to be interpreted in the natural way (at least in the Element client).

e.g.. this: 

```
matrix-commander -m 'testing testing :collision:' 
```
matrix-commander -m 'testing testing :collision:'

I would expect the emoji short code to be replaced by the explosion/collision emoji character, as it is in this github markdown interface.  In Element, this does not happen with a message received from matrix-commander, regardless of whether the --markdown flag is used or not.

UPDATE: I figured out you can craft emojis with unicode characters in a message submitted as HTML.  Would it make sense to add this as an example to the examples script, so that at least people can find out how to initiate emojis in their messages from matrix-commander?

```
matrix-commander -m 'testing testing &#x1F4A5;  ' --html
```

I still like the idea of interpreting the shortcodes in e.g. markdown mode.

**Comment by 8go** [comment]
Excellent :clap:   :clap:
