### ISSUE TITLE
Troubleshooting the "-m _" Stream Pipe Command 

### ISSUE THREAD

**Issue by skydiablo** [8go/matrix-commander#143]
I have two systems, both Ubuntu 22.04, one is a server, and the other is a desktop. On my desktop, I can work perfectly with the stream pipe magic character "-m _". However, when I do the same on my server via SSH, it prints the underscore directly in the matrix room, and the matrix commander command terminates.
Are there any ideas on what I can do? I am open to receiving requests to figure out where the differences are. Alternative pipe variants with "echo foo | ... -m -" work, as well as direct input of text "... -m test."
At the end, I use this feature in another software and repeatedly pipe my texts into the matrix commander as needed. It works very quickly and efficiently on my development machine, but not on the production system.

regards, volker.

**Comment by skydiablo** [comment]
okay, i have added the "--debug" flag and so i can see this:

my desktop:
DEBUG: matrix-commander: Stdin pipe is assigned to "message".
DEBUG: matrix-commander: Messages from pipe:         []
DEBUG: matrix-commander: Messages from keyboard:     []
DEBUG: matrix-commander: Messages from command-line: []
DEBUG: matrix-commander: stdin is ready. Something is definitely piped into program from stdin. Reading message from stdin pipe.

Sure, this only occurs if I reapply type in some text after running the matrix-commander. If I don't put in some text, it will just stop the run, and nothing happens.

my live environment:
DEBUG: matrix-commander: Stdin pipe is assigned to "none".
DEBUG: matrix-commander: Messages from pipe:         []
DEBUG: matrix-commander: Messages from keyboard:     []
DEBUG: matrix-commander: Messages from command-line: ['_']

Maybe it will help to debug this problem?

**Comment by skydiablo** [comment]
OH Fuck! my live env has an very old version like v3.5.19 .... *facepalm*
nevermind, it was my fault!

thx for attention, regards, volker...

**Comment by 8go** [comment]
Glad it got sorted out :wink:
