### ISSUE TITLE
"--log-level" not correctly forwarded to nio library

### ISSUE THREAD

**Issue by ManOrs88** [8go/matrix-commander#148]
hello,

with latest matrix-nio release (seen on 0.21.2, not sure since when the behavior it's present),
the log level set from matrix-commander cli appears to be ignored, nio messages always are at INFO level

this generates some clutter if you have an automated script and only want warnings and up,
or if you want more debug messages, as in both cases you get "info" level from nio

regards,
manuel

**Comment by 0ranki** [comment]
`matrix-nio` 0.20.0 works as it should

**Comment by 0x766C70** [comment]
same here with Version: 0.22.0

**Comment by 8go** [comment]
Thank you @0ranki and @0x766C70 for chiming in here.

**Comment by 8go** [comment]
I tested the following: 

Python 3.11 and matrix-nio 0.22.0 on Linux

Python 3.11 and matrix-nio 0.22.1 on Linux

```
matrix-commander -m test --log-level INFO DEBUG
matrix-commander -m test --log-level INFO INFO
matrix-commander -m test --log-level INFO WARNING
```

All is working correctly. I cannot reproduce your (bad) behavior with `matrix-nio 0.22.*`. I suggest you upgrade to `matrix-nio 0.22.1`. If you can re-produce the error there re-open the issue.

**Comment by ManOrs88** [comment]
hello @8go ,

with your syntax it is working as expected,
I was not specifying both log levels, only the first one, so it was an error on my side

I'm not sure why it was behaving differently before my initial report, maybe `matrix-nio` was not emitting those info level messages

thanks a lot for the help,
manuel

**Comment by 8go** [comment]
But yes, `matrix-nio` now prints more information on level `INFO`, so running the same `mc` command as before might result in more debug output. That's because `martix-nio` has changed. To avoid this use e.g. `--log-level INFO WARNING` or similar.
