### ISSUE TITLE
Waiting for you to accept on your other session

### ISSUE THREAD

**Issue by snan** [8go/matrix-commander#16]
Element sees when I do stuff with `matrix-commander` and asks "New login. Was this you?" I say yeah and then Element says "Verify other session. Waiting for you to accept on your other session…" and spins a ball forever.

**Comment by snan** [comment]
To solve, hit later and do an emoji verification explicitly. That works fine♥

**Comment by chagai95** [comment]
was not working for me so I did verify manually by text found that in Security & privacy settings

**Comment by 8go** [comment]
@snan Thank you for chiming in and helping out! I am thankful for your action. So, thanks @snan! <3

@chagai95 Not sure what to tell you. I have done this many times and it always worked for me. 

You have to start the matrix-commander with the `--verify` option. Then when you see  "New login. Was this you?" on e.g. Element, you say "Yes" and advance to emoji-verification. Once emoji verification is initiated e.g. via Element then you will get emojis printed inside the matrix-commander. You follow the instructions on both sides and at the end, the matrix-commander is verified and both devices know that they are verified.

If you feel like it, try again, following these instructions. But I am glad a manual verification worked for you. I always do the emoji verification. 

Good luck and thanks to both!

**Comment by xloem** [comment]
Emoji verification is also not working for me.  When I specify to verify by emoji on my other client, it simply hangs saying "Please wait..." .  There is no further output on matrix-commander:
```
2021-12-01 04:30:11,807:    DEBUG: matrix-commander: Trying path "/home/user/.config/matrix-commander/credentials.json" as last resort. Suggesting to look for it there.
2021-12-01 04:30:11,807:    DEBUG: matrix-commander: We found the file. It exists in the last resort directory "/home/user/.config/matrix-commander/credentials.json". Suggesting to use this one.
2021-12-01 04:30:11,807:    DEBUG: matrix-commander: Store was not found in default local directory. But found an existing store directory in "/home/user/.local/share/matrix-commander/store" directory. It will be used.
2021-12-01 04:30:11,807:    DEBUG: matrix-commander: Credentials file does exist.
2021-12-01 04:30:11,824:    DEBUG: matrix-commander: Logged in using stored credentials from credentials file "/home/user/.config/matrix-commander/credentials.json".
2021-12-01 04:30:11,824:    DEBUG: matrix-commander: Logged_in() = True
This program is ready and waiting for the other party to initiate an emoji verification with us by selecting "Verify by Emoji"in their Matrix client.
```

I've been politically targeted involving device compromise, so there could feasibly be something funny going on.  I've never gotten matrix-commander to work for me before, and am trying harder today.

I don't know how chagai95 verified manually by text (which for me displays the session id and session key to compare visually) given that matrix-commander doesn't support text verification yet, but I'm looking through the source code to see if I can ind the session key and proceed that way.

**Comment by chagai95** [comment]
I verified manually via Element.

**Comment by xloem** [comment]
Where are the matrix-commander keys shown to verify against the element keys?

**Comment by chagai95** [comment]
I verified the client

**Comment by xloem** [comment]
Do you understand that verifying means checking that the keys on both devices are the same?

**Comment by chagai95** [comment]
Well, as well but also verifying that it's you no?

**Comment by xloem** [comment]
There is no verification that it is you unless you verify the key is the same.

**Comment by chagai95** [comment]
Or by taking the risk of verifying it manually, apparently they allow that on the Element client so it's not that far fetched 😉

**Comment by xloem** [comment]
Do you mean taking the risk of marking the device as verified, when you have not actually manually compared the keys?

**Comment by KizzyCode** [comment]
For other people who have the same problem: what worked for me was to initiate verification _from the room panel_ where the matrix-commander-client is a member, and _not_ from the settings panel.
