### ISSUE TITLE
Python 3.10 is not supported

### ISSUE THREAD

**Issue by fuchs-fabian** [8go/matrix-commander#168]
The documentation says 3.8+, but 3.10 does not work either. This should be updated.

**Comment by ccgarant** [comment]
I have it running well on python 3.12.2 on my raspi. What device (arm, amd 32 or 64 bit?) and OS are you running on?

**Comment by fuchs-fabian** [comment]
- amd 64
- Fedora Linux 39 (Workstation Edition) - Gnome 45.5

Yes, I installed libolm-dev first.

But this is working now: https://github.com/fuchs-fabian/Checkmk-Matrix-Notifications
Here I have noted all the steps I have taken. It works on a Linux server, but I had problems on Fedora.

**Comment by 8go** [comment]
Thank you @fuchs-fabian for bringing this to my attention. :clap: 

In release 7.6.2 dependency has been bumped from Py 3.8 to Py 3.11. 

Thanks also to @ccgarant for chiming in. 

If there is still an issue, don't hesitate to re-open issue.
