### ISSUE TITLE
LOG Level

### ISSUE THREAD

**Issue by vlp-git** [8go/matrix-commander#17]
Hello !!

Thanks for this api !! I use it for a nice bot in Rust :)

Just a question: since your recent changes, I have notice that the log level is set to INFO & ERROR by default.
Before, I only had only ERROR by default.

I can just add "--log-level ERROR" to have only error ?

Thanks !!

**Comment by 8go** [comment]
You can now set 2 log levels:
a) the log-level for the lower level libraries
b) a log level for matrix-commander itself

You can use `--log-level ERROR ERROR` to set both levels to ERROR. 
I think this is what you want. 

I hope this helps @vlp-git 

Also, there was a new release today, see commit  from today. Commit 975b0380b9a1415397ff81c215c30bcfb5a4965b
