### ISSUE TITLE
Broken link for matrix-commander-tui

### ISSUE THREAD

**Issue by ccgarant** [8go/matrix-commander#170]
We get a 404 page not found for the matrix-commander-tui link

https://github.com/8go/matrix-commander/blob/79a5d0c2db9b3c49de0d0538affbe07f1a266f84/README.md?plain=1#L2038

**Comment by ccgarant** [comment]
I believe the path you want is matrix_commander/matrix-commander-tui ?

**Comment by 8go** [comment]
Yes, thank you  @ccgarant for finding the issue! Fixed in [078da5f](https://github.com/8go/matrix-commander/commit/078da5f16c9b94893939ad19a21677f84a8625f9)

:clap:
