### ISSUE TITLE
please give a warning if user picks all option for logout

### ISSUE THREAD

**Issue by ninchuka** [8go/matrix-commander#174]
I didnt realize it meant log out of ALL of my sessions 😅

**Comment by 8go** [comment]
Thanks for the comment.

But printing a warning will not help much, as it will not wait for user confirmation. It is a CLI and will try to do without user interaction as much as possible. If a warning is printed , it will still go on and logout. 

Another idea? Please re-open issue if so.

**Comment by ninchuka** [comment]
would it not be possible to have it wait for the user to enter "I UNDERSTAND THIS WILL LOG OUT ALL SESSION OF THIS ACCOUNT" before it logs out all sessions?
