### ISSUE TITLE
Getting this Error in logs when trying to run -d

### ISSUE THREAD

**Issue by chagai95** [8go/matrix-commander#18]
```Traceback (most recent call last):
  File "matrix-commander.py", line 3912, in <module>
    if len(pargs.log_level) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by 8go** [comment]
You are correct. As a matter of fact I found that bug too.

Thanks @chagai95 for pointing it out. It is appreciated! 

Fixed in commit 975b0380b9a1415397ff81c215c30bcfb5a4965b.
Test it and I hope this will fix it for you. If not, please reopen the issue.

Thanks again.
