### ISSUE TITLE
Taking a long time to send a message

### ISSUE THREAD

**Issue by chagai95** [8go/matrix-commander#19]
messages take 30 seconds until they get sent

https://nextcloud.chagai.website/s/rB4gQXE9bL2xGK2

**Comment by 8go** [comment]
Hi @chagai95 

For me, sending a single tiny 10 byte message takes about 4 seconds. 
Something like this: `time echo Hello | matrix-commander.py`
For my set-up and my configuration that is normal.

Of course performance depends on your hardware, your database, your message size, how many messages, your log level, your network speed, etc.

You can try to use logging levels and the timestamps in the logging output to figure out where the time is spent.

**Comment by chagai95** [comment]
ok weird, I think it's not a performance issue I have seen it work faster on the same machine with a different case
