### ISSUE TITLE
How to use e2e encryption with recovery key?

### ISSUE THREAD

**Issue by DAMO238** [8go/matrix-commander#2]
I have created an account on my homeserver for my bot. I cloned this repo and made a virtualenv with the required modules. I then invoked `./matrix-commander.py` and put in my details. At no point did it ask for my recovery key, so it cannot read any messages in encrypted rooms, it cannot do verification, and the messages it does send come up as 'not encrypted'. How do I give the bot the recovery key?

**Comment by DAMO238** [comment]
Well, as is typical, the problem solved itself. Suddenly, it just started being able to decrypt messages and encrypt them. I guess my server was just being slow or something...

**Comment by 8go** [comment]
Glad to hear that it is resolved. Have fun and enjoy!
