### ISSUE TITLE
Feature request: add bash auto-complete file

### ISSUE THREAD

**Issue by 8go** [8go/matrix-commander#21]
Add bash auto-complete file for bash auto completion when TAB is used.

**Comment by mizlan** [comment]
I have some experience with this so I can try doing this.

**Comment by 8go** [comment]
This would be excellent. Thank you for offering @mizlan !  Very kind of you.

I would be happy to pull it into the release and give you credit if you provide a PR.

All power to you! Thanks. :+1:

**Comment by mizlan** [comment]
Some of the options seem to ask for a room. Autocompleting this is possible, but would not be very ergonomic without some sort of caching. (We wouldn't want to be sending a network request for autocomplete). Is there already such a cache?

**Comment by 8go** [comment]
No, there is no cache of room names. Rooms names are only obtainable via database query or network query.

I think the user must enter/type his/her room names "manually", this is usually done via copy/paste anyway.
