### ISSUE TITLE
using multiple credentials

### ISSUE THREAD

**Issue by hitchhooker** [8go/matrix-commander#23]
If you plan on having many credential files,
consider moving them to directory "/root/.config/matrix-commander".

can you give an example how multiple credentials can currently be used with matrix-commander?

**Comment by 8go** [comment]
Hi @hitchhooker 

You might have multiple accounts, i.e. multiple users. If so, you can set up a credentials file for usr1 and another credentials file for usr2. One can then use `matrix-commander` to send as user 1 or as user 2.

`matrix-commander.py --credentials usr1roomA.json # select credentials file`
`matrix-commander.py --credentials usr2roomB.json # select credentials file`
