### ISSUE TITLE
Tips on how to compile Docker image for ARM32 (Raspberry Pi)

### ISSUE THREAD

**Issue by sunrisepi** [8go/matrix-commander#25]
Hi.  I was able to compile the Docker image for matrix-commander for use on my Raspberry Pi (4b, 32bit, running buster of Raspberry Pi OS).  Sharing this information in case it is helpful to others.  Thanks very much for Matrix Commander, I like that this E2EE client is so easy to use!  The documentation is also excellent.

Changes I had to make for the Dockerfile:
1. I had to include **pip3 install wheel** as I was receiving an error that "wheel" wasn't found.
2. I had to update **dnf** to also install **libffi-devel, libjpeg-devel and zlib-devel** due to missing dependencies/libraries for cffi and Pillow. I learned about this from the [Pillow installation webpage](https://pillow.readthedocs.io/en/latest/installation.html#building-on-linux).  Even though it lists several dependencies, I just kept adding them one by one until build errors stopped and the build finished successfully.  I ended up only having to add 2 more, so I believe that means the other dependencies are already satisfied by the existing requirements/installed packages.

A few observations and questions:
- In Rasperry Pi OS, I can't use **!YourRoomId:example.org** to specify a room for sending a message.  I need to use 
**\#YourRoomId:example.org** instead.  I tried escaping the ! (like **\\!)** but that didn't work either.
- The Docker image that was built is very large... 624MB! Any tips on how to reduce the image size?
- Is it possible to send message room data as JSON?  I haven't tested this with the -code parameter yet, but was wondering if that would work.

I have highlighted below the Docker file updates I made (they're in **bold text)**.  Thanks!

> FROM fedora:33
> 
> RUN dnf install -y pip libolm-devel gcc python-devel python3-dbus **libffi-devel libjpeg-devel zlib-devel**
> 
> WORKDIR /app
> 
> COPY requirements.txt .
> COPY matrix-commander.py .
> 
> RUN **pip3 install wheel &&** pip3 install -r /app/requirements.txt
> 
> VOLUME /data
> 
> ENTRYPOINT ["/bin/python3", "/app/matrix-commander.py" ,"-s", "/data/store", "-c", "/data/credentials.json"]

**Comment by 8go** [comment]
Thank you @sunrisepi 

Excellent job and thank you for contributing and sharing this with the community. 
I updated this in commits https://github.com/8go/matrix-commander/commit/5089d71513685bec6443388dcd105d177191a25e and https://github.com/8go/matrix-commander/commit/ccde2085c5e1413e89127c06fd5428182a04cf2b.

Very helpful! Thanks again @sunrisepi

**Comment by 8go** [comment]
Regarding: In Rasperry Pi OS, I can't use !YourRoomId:example.org to specify a room for sending a message. I need to use
#YourRoomId:example.org instead. I tried escaping the ! (like \!) but that didn't work either.

There are 2 different concepts: 
- room id
- room alias

Room ids have a syntax with  `!....`. Room aliases have a syntax with `#...`. You can find the formal syntax specification in Matrix documentation. So, I think you are mixing up room id and room alias. If you go under room settings in your client, e.g. Element, then you should see both. A room id is always required. A room alias is optional. 

matrix-commander understands both room ids and room aliases. Find the correct room id and the `!...` will work too.

Also, you can test in your Element client. Look carefully at the URL! Look for `https://element.test.org/#/room/!...` and `https://element.test.org/#/room/#...`. Element URLs also understand both, room ids and room aliases. You can test your ids and aliases in the Element URLs.

**Comment by 8go** [comment]
Regarding: The Docker image that was built is very large... 624MB! Any tips on how to reduce the image size?

No, I don't know. Can anyone from the community help out? Does anyone have any suggestions? Please comment here if you can contribute with some ideas/suggestions/tips.

**Comment by 8go** [comment]
Regarding: Is it possible to send message room data as JSON? I haven't tested this with the -code parameter yet, but was wondering if that would work.

Please open another new issue so that we separate issues. GitHub search will be more productive for others this way. Thanks.

**Comment by sunrisepi** [comment]
> 
> 
> Regarding: In Rasperry Pi OS, I can't use !YourRoomId:example.org to specify a room for sending a message. I need to use
> #YourRoomId:example.org instead. I tried escaping the ! (like !) but that didn't work either.
> 
> There are 2 different concepts:
> 
>     * room id
> 
>     * room alias
> 
> 
> Room ids have a syntax with `!....`. Room aliases have a syntax with `#...`. You can find the formal syntax specification in Matrix documentation. So, I think you are mixing up room id and room alias. If you go under room settings in your client, e.g. Element, then you should see both. A room id is always required. A room alias is optional.
> 
> matrix-commander understands both room ids and room aliases. Find the correct room id and the `!...` will work too.
> 
> Also, you can test in your Element client. Look carefully at the URL! Look for `https://element.test.org/#/room/!...` and `https://element.test.org/#/room/#...`. Element URLs also understand both, room ids and room aliases. You can test your ids and aliases in the Element URLs.

@8go, thank you!  This helped me understand I was confusing the terms.  This works now for room id (I had to escape **!** with **\\** when specifying the roomid via the **-r** parameter, which is expected).

`docker run --rm -v ./data:/data matrix-commander -r "\!{myRoomId}:matrix.org" -m "Sending to room ID"`

**Comment by sunrisepi** [comment]
> 
> 
> Regarding: Is it possible to send message room data as JSON? I haven't tested this with the -code parameter yet, but was wondering if that would work.
> 
> Please open another new issue so that we separate issues. GitHub search will be more productive for others this way. Thanks.

Thanks @8go.  I've created 2 new issues to track the questions I am seeing with respect to sending messages via Matrix Commander as code.  Thanks a bunch for Matrix Commander, it is a cool utility! 👏 

Issues:  #26 , #27

**Comment by 8go** [comment]
Thank you for separating the issues, one specific "problem" per github issue. More clarity for all and for future readers.

Thanks for your contributions @sunrisepi
