### ISSUE TITLE
sending messages with JSON, HTML, XML, YAML, etc data format

### ISSUE THREAD

**Issue by sunrisepi** [8go/matrix-commander#26]
I'm trying to send JSON data elements as a message to my Matrix room, using Matrix Commander.  It is working really great for regular messages (thanks!), but for JSON I was getting weird results.  But then I realized I had a quoting issue. 

I'm sure this is obvious to others, but it tripped me up for a while (or, maybe it is just too late and I need to go to bed 😆 ).  Let me summarize my journey.

I figured out I could get Matrix Commander to send message as code by using `-k -m {message}` (or `--code -m {message}`), per the info at https://github.com/8go/matrix-commander#examples-of-calling-matrix-commander. 

**Trying to simulate sending JSON data as code, by sending message surrounded in braces containing 2 elements, with data for each element in quotes. This results in 3 messages sent.. realized it was because `-m` is expecting a parameter that was quoted, and I was trying to quote yet again, so double quoting was happening and 3 messages were sent instead of just 1:**
```
pi@pi:$ docker run --rm -v ./data:/data matrix-commander -k -m "{title: "hello", message: "here it is"}"
2021-04-08 05:27:32,532:     INFO: matrix-commander: This message was sent: "{title: hello, message: here" to room "!{roomId}:matrix.org".
2021-04-08 05:27:33,027:     INFO: matrix-commander: This message was sent: "it" to room "!{roomId}:matrix.org".
2021-04-08 05:27:33,496:     INFO: matrix-commander: This message was sent: "is}" to room "!{roomId}:matrix.org".
pi@pi:$
```
**When I try the same thing but with the data elements having no quotes, it sends only 1 message as expected.**
```
pi@pi:$ docker run --rm -v ./data:/data matrix-commander -k -m "{title: hello, message: here it is}"
2021-04-08 05:28:29,902:     INFO: matrix-commander: This message was sent: "{title: hello, message: here it is}" to room "!{roomId}:matrix.org".
pi@pi:$
```
**It also works with single quotes.**
```
pi@pi:$ docker run --rm -v ./data:/data matrix-commander -k -m "{title: 'hello', message: 'here it is'}"
2021-04-08 05:29:32,252:     INFO: matrix-commander: This message was sent: "{title: 'hello', message: 'here it is'}" to room "!{roomId}:matrix.org".
```
**And, finally, got it working like I wanted by using `-m '{message}'` .. note the single quotes around the parameter for `-m` below**
```
pi@pi:$ docker run --rm -v ./data:/data matrix-commander --code -m '{title: "hello", message: "here it is"}'
2021-04-08 05:48:58,278:     INFO: matrix-commander: This message was sent: "{title: "hello", message: "here it is"}" to room "!{roomId}:matrix.org".
```
I realize this may be obvious, but perhaps it would be helpful to include a note about this in the documentation?  That is:  If the message to be sent needs to include quotes, then ensure the parameter to `-m` is surrounded in single quotes.  

Thanks for considering my suggestion! 😄

**Comment by 8go** [comment]
Thank you @sunrisepi for bringing up this question.

Also thanks for answering it yourself. 

Yes, one can send any kind of formatted text, such as JSON, YAML, XML, HTML, or whatever it might be. It all works.

When providing the arguments one needs to understand Bash (as you are running a Bash command). 

So: 
```
matrix-commander -k -m "{title: "hello", message: "here it is"}"
```
will fail! Of course, you are sending an invalid bash string.

```
matrix-commander -k -m '{title: "hello", message: "here it is"}'
```
will work. A valid bash string.

```
matrix-commander -k -m "{title: \"hello\", message: \"here it is\"}"
```
will work. A valid bash string. You have to escape the double-quotes!

The preferred method is: 
```
matrix-commander -k -m "{title: \"${TITLE}\", message: \"${SOMETEXT}\"}"
```
as this allows also embedding bash variables. 

```
matrix-commander -k -m '{title: "${TITLE}", message: "${SOMETEXT}"}'
```
will NOT work. It will not do what you think it should do. Test it out.

Thanks @sunrisepi  for sharing this with other people, so other people can learn as well. 
But this is basic Bash knowledge, people are kind of expected to know Bash, 


Added :
```
$ # example of how to quote text correctly, e.g. JSON text
$ matrix-commander -m '{title: "hello", message: "here it is"}'
$ matrix-commander -m "{title: \"hello\", message: \"here it is\"}"
$ matrix-commander -m "{title: \"${TITLE}\", message: \"${MSG}\"}"
$ matrix-commander -m "Don't do this"
$ matrix-commander -m 'He said "No" to me.'
```
