### ISSUE TITLE
How to send message via docker and via piped input, How to use pipes with docker

### ISSUE THREAD

**Issue by sunrisepi** [8go/matrix-commander#27]
I'm using an ARM processor (Raspberry Pi 4B, 32-bit OS, Raspberry Pi OS/buster).  Compiled my own docker image of Matrix Commander and I've noticed a given example doesn't seem to work on my system.  Could this be a bug?

**Example given at https://github.com/8go/matrix-commander#examples-of-calling-matrix-commander, in the documentation, to send a message as code:**
`df -h | matrix-commander.py --code # formatting for code/tables`

**However, when I run it, this doesn't work.. bug? Just runs then exits to terminal with no output.  I verified the room didn't receive any data.**
`df -h | docker run --rm -v ./data:/data matrix-commander --code`

Thanks for any info! 😉

**Comment by sunrisepi** [comment]
I think I may have figured this out... does **docker run** not accept piped input?

I tried the following and it seemed to work.  I'm not using piped input to the **docker run** command, but command substitution to pass the output as a message to matrix commander.  I think it accomplished the same thing.

```
pi@pi: $ docker run --rm -ti -v ./data:/data matrix-commander -k -m "$(df -h| head -2)"
2021-04-08 06:52:56,195:     INFO: matrix-commander: This message was sent: "Filesystem                   Size  Used Avail Use% Mounted on
/dev/root                    110G   26G   81G  24% /" to room "!{roomId}:matrix.org".
pi@pi: $

```

Aha!  You can use piped input with docker, but you need to update the parameters for the **docker run** command.  This works (need to remove **-t**):
```
pi@pi: $ df -h | head -2 | docker run --rm -i -v /home/pi/dockerapps/matrix-commander/data:/data matrix-commander-headless -k
2021-04-08 06:59:49,193:     INFO: matrix-commander: This message was sent: "Filesystem                   Size  Used Avail Use% Mounted on
/dev/root                    110G   26G   81G  24% /" to room "!{roomId}:matrix.org".
pi@pi: $
```

This is explained here:  https://docs.docker.com/engine/reference/run/.  As noted below:

**For interactive processes (like a shell), you must use -i -t together in order to allocate a tty for the container process. -i -t is often written -it as you’ll see in later examples. Specifying -t is forbidden when the client is receiving its standard input from a pipe, as in:**

> $ echo test | docker run -i busybox cat

Fascinating.  Well, not sure if you want to add a note on this to the documentation for the **docker run** examples, but others may find it helpful.  It would have saved me 30 minutes of troubleshooting.  😆 Thanks!

**Comment by 8go** [comment]
Thank you @sunrisepi 

Yes, this is an issue specific to docker and has nothing to do. But it is great that you summarized it here for other to share.
Great community work. Thank you! :+1: 

Your contribution is merged in https://github.com/8go/matrix-commander/commit/fb7d1ee685dddb9cadf5554351480ffadb8a29cb 

Lovely and thanks again!
