### ISSUE TITLE
Question: Is it possible to send feature-rich messages to rooms with matrix-commander?

### ISSUE THREAD

**Issue by sunrisepi** [8go/matrix-commander#28]
Hi.  I am wondering if we can use matrix-commander to send something that looks as good as the below screenshot, which was sent to Discord (using a Discord webhook):  https://birdie0.github.io/discord-webhooks-guide/discord_webhook.html

I see that matrix-commander supports a subset of HTML, but am wondering if anyone has some working example code/HTML snippets they could share.  I am interested in what others have done to this point.  I am just getting started, so looking forward to learning more about how far we can take the formatting of messages.  😄  

I like Discord, but the things that annoy me about it are (a) I have no control over the data [it is stored on their servers] and (b) there is no end-to-end encryption.  Hence I would like to use Matrix for this type of content, but am wondering if it is possible. Thanks.
![image](https://user-images.githubusercontent.com/63925343/114237388-e50cbb80-9937-11eb-89f0-c9cc85841815.png)

**Comment by 8go** [comment]
@sunrisepi thanks for your question.

I can tell you that Matrix, or Element do not support full HTML, they support a subset of HTML. 

Whatever HTML subset is supported by Element/Matrix, is also supported by `matrix-commander`.

You must set the `markdown_convert` and `formatted` fields to `true` in the Yaml config file. 

I have no time to test this right now and send you example code, maybe somebody else can chime in and assist. I am too busy at the moment. 

Regarding the image: You cannot embed it directly into a message.  Element does not allow that. You have to send the image separately.

**Comment by 8go** [comment]
Closing question. Reopen it once Matrix allows embedding images in messages (which is not very likely to occurr).
