### ISSUE TITLE
license clarification: gpl3 or "gpl3 or later"

### ISSUE THREAD

**Issue by seb314** [8go/matrix-commander#29]
I' currently trying to [package](https://github.com/NixOS/nixpkgs/pull/119895) matrix-commander for nix.
In order to add the package to nixpkgs, it would be good to know if the common "...version 3 of the License, **or (at your option) any later version**"  rule applies to matrix-commander too.

The topic is described in more detail [here](https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md)

Thanks!

**Comment by 8go** [comment]
Hello @seb314 

Thank you for your effort to package matrix-commander for nix. This is great! I appreciate your effort.

Currently it is set to "gpl 3 only" but I am open for suggestions.
Would you prefer "gpl3 or later"?

Is there anything else I can do to help you?

**Comment by seb314** [comment]
Hi @8go

thanks for the clarification! 
I only learned about this distinction recently, so I don't know if there are potential drawbacks of gpl3Plus, but the most convincing argument in favor of  gplxPlus is this one:

> Publishing programs with license upgrade permission is vital to avoid incompatibility between programs released under different GPL versions.
> Two different copyleft licenses are almost inevitably incompatible in the absence of some explicit compatibility mechanism. That is because each one necessarily requires modified versions of a program to be released under that very same license. As a consequence, code released under GPL version 2 only can't be merged with code released under GPL version 3 only.

from [this article on gnu.org](https://www.gnu.org/licenses/identify-licenses-clearly.html), which goes into a lot more detail.

**Comment by 8go** [comment]
OK, hi @seb314 

I have read through your links. Thanks for providing them. Since it seems better to have GPL3Plus, I have switched today from GPL3ONLY to GPL3PLUS. 

See also "License" text in README and in source code. 

License text reads as follows:

```
License

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

When preparing to package matrix-commander for NIX the question came up if matrix-commander is GPL3Only or GPL3Plus. GPL3PLus was deemed to be better. As such the license was changed from GPL3Only to GPL3Plus on May 25, 2021. Versions before this date are licensed under GPL3. Versions on or after this date are GPL3Plus, i.e. GPL3 or later.

See GPL3 at FSF.
```

OK with you @seb314 ?

**Comment by seb314** [comment]
great, thank you!
I created a [PR](https://github.com/NixOS/nixpkgs/pull/125700) with the license update at the nixpgs repo.

**Comment by 8go** [comment]
thank you @seb314
