### ISSUE TITLE
Doesn't seem to upload attachments encrypted

### ISSUE THREAD

**Issue by pelzvieh** [8go/matrix-commander#32]
From reading the source of send_file or send_image, I believe any attachment is uploaded unecrypted and will be readable for anyone in possession of the URL. [Matrix documentation](https://matrix.org/docs/spec/client_server/latest#sending-encrypted-attachments) states that must be encrypted using one-time key and iv resp. and the decryption information be included with the room event.

**Comment by 8go** [comment]
This is fantastic!  

Thank you for finding this weak spot, this security weakness. And even more thanks for fixing it. 

I greatly appreciate it and I am sure all the other users will appreciate it too. 

Thanks again @pelzvieh  

 :heart: your PR.   :+1:
