### ISSUE TITLE
Provide a requirements.txt file?

### ISSUE THREAD

**Issue by Ezwen** [8go/matrix-commander#4]
Installing dependencies would be much easier if a `requirements.txt` file was provided. Then anyone could just create a virtualenv and run `pip install -r requirements.txt` and be ready to go :).

**Comment by 8go** [comment]
@Ezwen Good idea. Thanks for pointing it out.
Will do it today.

**Comment by 8go** [comment]
Done. Test it out and see if it works for you! Thanks again @Ezwen

**Comment by Ezwen** [comment]
thanks :)! I had to change the file a little to make it work, the changes I made are part of the PR I made here: https://github.com/8go/matrix-commander/pull/5

I can make a separate PR for the `requirements.txt` file if you prefer.

**Comment by 8go** [comment]
Excellent @Ezwen 
This will be generally useful to many people. 
Your contribution is highly appreciated. :+1: 
Thank you very much.
