### ISSUE TITLE
Feature Request: option for listing room members

### ISSUE THREAD

**Issue by pacien** [8go/matrix-commander#41]
It would be nice to have a sub-command to list all the members of a given room.

**Comment by 8go** [comment]
Thanks @pacien :+1:

That would be a valid, nice feature. 

Anyone out there would like to step forward and provide a PR for this feature?

**Comment by 8go** [comment]
@pacien and @jannctu 

After patient waiting, here it is. Have a look at commit [acb4bde](https://github.com/8go/matrix-commander/commit/acb4bde0a8d00bb3396f4f765a8c35714e12f37e)

```
  --joined-rooms        Print the list of joined rooms. All rooms that you are
                        a member of will be printed, one room per line.
  --joined-members JOINED_MEMBERS [JOINED_MEMBERS ...]
                        Print the list of joined members for one or multiple
                        rooms. If you want to print the joined members of all
                        rooms that you are member of, then use the special
                        character '*'.
```

**Comment by 8go** [comment]
Implemented. Done. Closing it.
