### ISSUE TITLE
commander hangs when called by other program n8n or rundeck

### ISSUE THREAD

**Issue by vit76** [8go/matrix-commander#42]
I am trying to have a webhook (n8n or rundeck) call matrix through a execute command, however the workflow always hangs, it shows up in running process but doesn't send message until you manually stop the workflow or kill the process.

Works fine if I run it locally as a logged in user but fails if I use another program n8n or rundeck to run the program both hang which leads me to believe its matrix-commander keeping the process running for some reason

```
python3 /opt/matrix-commander/matrix-commander.py --log-level ERROR -c /opt/matrix-commander/credentials.json -s /opt/matrix-commander/store -m hi
```
![image](https://user-images.githubusercontent.com/64735871/125165792-8a694280-e166-11eb-962f-fed8a43ad4d3.png)
Even simple execute command hangs

Goal
![image](https://user-images.githubusercontent.com/64735871/125165870-d4eabf00-e166-11eb-847b-d48a5028672f.png)

**Comment by vit76** [comment]
figured it out had to add "echo |" before the command, now it works as expected.

echo | matrix-commander.py -m message

**Comment by 8go** [comment]
@vit76 :: Glad that it is working for you now. :clap:
