### ISSUE TITLE
Feature Request: Upload to pypi

### ISSUE THREAD

**Issue by iexos** [8go/matrix-commander#43]
Hi,

it would be great to be able to install simply via `pip install matrix-commander` :)

**Comment by 8go** [comment]
Hi @iexos 

Thanks :clap: for the input. Your suggestion is welcome. :+1: I will put this on my to-do list. 

Give me some time, I will eventually do it.

**Comment by 8go** [comment]
Done. See commit [08e5859](https://github.com/8go/matrix-commander/commit/08e5859107086f19cdabb26bca473415038296d8)

See also https://pypi.org/project/matrix-commander/

Ready to be installed via `pip --install matrix-commander`

**Comment by iexos** [comment]
Awesome, thank you!
