### ISSUE TITLE
bug: aiofiles dependency vs matrix-nio dependency

### ISSUE THREAD

**Issue by tobixen** [8go/matrix-commander#46]
matrix-nio 0.18.6 has requirement aiofiles<0.7.0,>=0.6.0, however in requirements.txt aiofiles has to be version 0.4 or 0.5.

Either it's needed to put some version restrictions on matrix-nio, or it's needed to make sure aiofiles 0.6 will work.

**Comment by 8go** [comment]
Thank you @tobixen 

Your input is valid and very welcome. Fixed in  7ab3fd9 

Your bug report is appreciated :+1:
