### ISSUE TITLE
[Feature request] Allow to disable SSL checks, allow to specify local SSL certificate file

### ISSUE THREAD

**Issue by opk12** [8go/matrix-commander#61]
If the certificate is self-signed, or the homeserver does not have a domain (think the typical self-hosted Synapse in a private network) then certificate checking will fail. AsyncClient accepts ssl=False to disable the checks on the certificate, so matrix-commander could have a flag that disables them.

**Comment by 8go** [comment]
This feature request has been implemented.

@opk12  please test it and verify that it works for you. Report back any successes! 

Implemented in commit [0abffd5](https://github.com/8go/matrix-commander/commit/0abffd5e07015bedcd719831c9a47589dbea802e).

**Comment by opk12** [comment]
Thank you! Could you add an option like `--certificate /path/to/certificate` ? Meanwhile, I have saved the certificate locally and call `AsyncClient(ssl=ssl.create_default_context(cafile="/path/to/certificate"))`, so I can keep HTTPS/TLS and let random guests join the WiFi. The option would do the same (pass the path to ssl, without opening the file).


I verified that `--no-ssl` works for me after applying this (if this is not applied, an exception is thrown):

```
725c725
< from aiohttp import ClientConnectorError, ClientSession, web
---
> from aiohttp import ClientConnectorError, ClientSession, web, TCPConnector
2563c2563,2564
<     async with ClientSession() as session:
---
>     connector = TCPConnector(ssl=False if pargs.no_ssl is True else None)
>     async with ClientSession(connector=connector) as session:
```

**Comment by 8go** [comment]
Thank you @opk12 for your testing and comments. 

I am not quiet sure I understand correctly.
- For a person who has no SSL cetificate, just using `--no-ssl` with the code as-is will not work and it will throw an error? Which one?
- Applying your suggested code (about 3 lines), then this is solved? 
Just confirm that this is correct and I will apply your suggested 3-line change.

Totally independent of this bug, you suggest a `--certificate` (would `--ssl-certificate` be better?) . This is independent of the above, right? 
- and according to your set-up this is also a 1-line code change (plus 30 lines of args related code), correct?

Did I understand things correctly? Am I wrong somewhere? Please :pray: provide feedback. 

If all goes well, I should be able to do it next week.

**Comment by opk12** [comment]
Thank you for the prompt reply. I copy-pasted the output below.

> For a person who has no SSL cetificate, just using --no-ssl with the code as-is will not work and it will throw an error?

I have a self-signed certificate and use `--no-ssl`, here is the output
```
$ matrix-commander.py --no-ssl
Could not find an existing store directory anywhere.
There are 2 possibilities:
[...]
Continue to create new credentials? (Yes or Ctrl-C to abort) Yes
Enter URL of your homeserver: [https://matrix.example.org] https://192.168.1.1:443
2022-05-19 15:51:04,898:     INFO: matrix-commander: SSL will be not be used. The SSL certificate validation will be skipped for this connection.
2022-05-19 15:51:12,035:    ERROR: matrix-commander: The program matrix-commander.py failed. Sorry. Here is the traceback.
2022-05-19 15:51:12,049:    ERROR: matrix-commander: Traceback (most recent call last):
  File "/tmp/tmp.EOIyuk9S0x/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/matrix-commander/matrix-commander.py", line 4324, in <module>
    asyncio.run(main_send())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/tmp/matrix-commander/matrix-commander.py", line 3392, in main_send
    await create_credentials_file(credentials_file, store_dir)
  File "/tmp/matrix-commander/matrix-commander.py", line 2564, in create_credentials_file
    async with session.get(
  File "/tmp/tmp.EOIyuk9S0x/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/tmp/tmp.EOIyuk9S0x/venv/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/tmp/tmp.EOIyuk9S0x/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/tmp/tmp.EOIyuk9S0x/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/tmp/tmp.EOIyuk9S0x/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/tmp/tmp.EOIyuk9S0x/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/tmp/tmp.EOIyuk9S0x/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host 192.168.1.1:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')]
```

> Applying your suggested code (about 3 lines), then this is solved?

Yes.
```
$ matrix-commander.py --no-ssl
Could not find an existing store directory anywhere.
There are 2 possibilities:
[...]
Continue to create new credentials? (Yes or Ctrl-C to abort) Yes                                                                
Enter URL of your homeserver: [https://matrix.example.org] https://192.168.1.1:443
2022-05-19 15:54:42,262:     INFO: matrix-commander: SSL will be not be used. The SSL certificate validation will be skipped for this connection.
Enter your full user ID: [@user:example.org] @test_1:192.168.1.1
Choose a name for this device: [matrix-commander] matrix-commander-05-19
Enter your room ID: [!SomeRoomIdString:example.org] !roomid:192.168.1.1
2022-05-19 15:55:06,925:     INFO: matrix-commander: The persistent storage directory store was created for you.
Password: 
Log in using a password was successful. Credentials were stored in file
"credentials.json". Run program "matrix-commander.py" again to login with
credentials and to send a message. If you plan on having many credential files,
consider moving them to directory "/tmp/tmp.TxLCuhjTul/.config/matrix-
commander".
```

> Totally independent of this bug, you suggest a `--certificate` (would `--ssl-certificate` be better?) . This is independent of the above, right?

Yes and `--ssl-certificate` would be more explicit.

>     * and according to your set-up this is also a 1-line code change (plus 30 lines of args related code), correct?

Yes. I am sorry that I did not update this ticket with my improved SSL handling earlier.

**Comment by opk12** [comment]
I see a pattern in matrix-nio (intended to mirror the same pattern in aiohttp): matrix-nio accepts a parameter `ssl: Union[None, SSLContext, bool]`.

`matrix-commander` currently repeats `(ssl=False if pargs.no_ssl is True else None)` in multiple places.

So what about making

    def make_ssl_argument_from_CLI_arguments(pargs_no_ssl, pargs_ssl_certificate) -> Union[None, SSLContext, bool]:

and pass the result everywhere it is needed?

**Comment by 8go** [comment]
Thank you for your input. This is very useful. This really helps understand the issue. Great feedback :clap:

:+1:  Looking into it.

**Comment by 8go** [comment]
@opk12 I just committed [b18a056](https://github.com/8go/matrix-commander/commit/b18a0561e17c08a6758ba1b2950556cd6928402f) 

Please have a look at it. 
- Does it satisfy what you wanted to do? 
- Does it pass all your test cases?
- Does it work for you without SSL certs (`--no-ssl`)? 
- Does it work with your own cert (`--ssl-certificate`)?

Please :pray: report back your feedback. :+1:

**Comment by opk12** [comment]
Thank you very much! For matrix-nio `ssl`, the docs needs updating ([issue](https://github.com/poljar/matrix-nio/issues/321))

These need handling before testing
1. [line 4623](https://github.com/8go/matrix-commander/blob/master/matrix-commander.py#L4623) `create_default_context` @ `initial_check_of_args`. This needs `try ... except` for at least `OSError` and `ssl.SSLError`.
    - `OSError` covers everything: file not found, file unreadable, is directory, corrupted physical disk blocks (file is readable but the disk errors out), connection error from a network mounted directory, ...
    - optionally, you can add the common cases `FileNotFoundError` and `PermissionError`, for user-friendly error messages. If not, they will be handled by `OSError`.
    - `ssl.SSLError` for invalid file content (is not a certificate).
2. Point 1 makes the check unnecessary at [line 3894](https://github.com/8go/matrix-commander/blob/master/matrix-commander.py#L3894) (*)
3. [line 4629](https://github.com/8go/matrix-commander/blob/master/matrix-commander.py#L4629) and [4635](https://github.com/8go/matrix-commander/blob/master/matrix-commander.py#L4635) `is` was likely meant to be `=`

(*) and in exotic cases that I do not use, the certificate will not be a regular file

**Comment by 8go** [comment]
All your 3 points from above are valid. 

All 3 are fixed in commit [d10ce45](https://github.com/8go/matrix-commander/commit/d10ce457aaff1e8f63c6d81c1e3a0d7c53964da5)

Thank also for creating a Issue (https://github.com/poljar/matrix-nio/issues/321) in `matrix-nio`.

Can you please :pray: look it over again and see if it works now for you?  Thank you :clap:

**Comment by opk12** [comment]
Thank you very much! Both work for me, `--ssl-certificate` with the self-signed certificate, and `--no-ssl` with http (no certificate).

**Comment by 8go** [comment]
Thank you :clap: @opk12 for reporting back. I am happy it works for you now. :rocket: 

Excellent. Closing issue how.
