### ISSUE TITLE
Question: Project status as of May 2022?

### ISSUE THREAD

**Issue by brevilo** [8go/matrix-commander#62]
Hi there!

What's the current status of this project? There had been rather constant development for a year but since roughly half a year there doesn't seem to be any activity anymore. Not complaining, just curious. It would be great to see this little gem flourish...

Thanks

**Comment by Jochem22** [comment]
I would like to know the same thing.

**Comment by ser** [comment]
it looks project is dead :(

**Comment by skydiablo** [comment]
maybe it is done? ;)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@skydiablo, no software is complete.

**Comment by Jochem22** [comment]
Any recommended alternatives?

**Comment by edwinsage** [comment]
I think this is still far more featureful than any other equivalents.  The underlying matrix-nio library is still being maintained, so this project still works even with changing Matrix standards.

That said, I think there are still a lot of improvements needed.  I've pulled in some changes that other people have made and added some of my own on my own fork (and made pull requests back here).  I'd love to see someone step up to maintain this or a fork.  I might do it myself, but as I don't actually write in Python (I'm a Perl guy) I feel like there has to be a better person than me.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@edwinsage, which pull-requests does http://github.com/8go/matrix-commander/issues/62#issuecomment-1125433714 reference?

**Comment by edwinsage** [comment]
The two changes I've opened PRs for are #65 and #67.  My own fork also pulls in #51 because why not, plus some other changes that I'm not convinced are fit/needed in upstream.

**Comment by 8go** [comment]
> The two changes I've opened PRs for are #65 and #67. My own fork also pulls in #51 because why not, plus some other changes that I'm not convinced are fit/needed in upstream.

Specifically responding to @edwinsage comment: All these PRs (#51, #65, #67) and others have been merged in.

**Comment by 8go** [comment]
As suggested in Issue #68 Github Discussions was enabled. Feel free to use it to discuss `matrix-commander` without having to go through an issue.

**Comment by xurizaemon** [comment]
Project is visibly active, I think this issue could be closed to tidy the queue.

**Comment by 8go** [comment]
As suggested, closing issue.
