### ISSUE TITLE
python-olm installation fails

### ISSUE THREAD

**Issue by genewitch** [8go/matrix-commander#63]
```
Installing collected packages: asyncio, argparse, python_magic, Pillow, importlib-metadata, cachetools, atomicwrites, python-olm, markdown, datetime, matrix-nio
  Running setup.py install for python-olm ... error
  error: subprocess-exited-with-error

  × Running setup.py install for python-olm did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      make: *** No rule to make target '../include/olm/olm.h', needed by 'include/olm/olm.h'.  Stop.
```

I know this isn't an issue with this repo, as i can't even get pip to install olm at all. I can compile it from the .git, though, but i am evidently too tired to get pip to recognize it. Should i complain to matrix's issues?

I was hoping to not have to code API access in python, but it looks like i might have to >.<

**Comment by themancalledjakob** [comment]
possibly you need to install ibolm-dev?

https://matrix-nio.readthedocs.io/en/latest/#installation

even though this is technically an issue from matrix-nio, i think that this could be mentioned in the README.md, since it is necessary to install matrix-commander.

**Comment by 8go** [comment]
I agree with @themancalledjakob 
This looks like a problem with the `libolm` installation. `libolm-dev` is the most likely culprit. Install it. Read the README regarding `libolm` installation. Then try again.  Report back @genewitch  if this solved your issue.

**Comment by 8go** [comment]
Closing issue. Re-open if necessary.
