### ISSUE TITLE
Please enable Discussion for this repository.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [8go/matrix-commander#68]
What I refer to is explained at `http://docs.github.com/discussions`. It shall allow questions to be asked without necessitating utilisation of `http://github.com/8go/matrix-commander/issues` unnecessarily.

**Comment by 8go** [comment]
Just done. Feel free to be the first one to comment in `Discussions`.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I am thankful.
