### ISSUE TITLE
Redact event

### ISSUE THREAD

**Issue by notramo** [8go/matrix-commander#7]
For this, we need to know the event ID. Maybe print those too on the start of the line with a switch?

**Comment by 8go** [comment]
See PR #14 
Event_id can now be printed. As last item in the list

E.g. line now looks something like this:

Message received for room Undetermined [!JHbgdhDGY:matrix.site.com] | sender John [@john:matrix.site.com] | 2021-02-04 18:16:51 | test4 | $jCaItuytsds765duTUYTUYT8TUTUYP

**Comment by 8go** [comment]
OK, looks done. Closing issue.
