### ISSUE TITLE
Enhancement: Publish Docker image on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [8go/matrix-commander#70]
It would make still easier to run the command and also keep it up to date.
For reference, [here](https://github.com/pataquets/docker-boinctui/blob/master/.github/workflows/docker-publish.yml) is a sample file of mine to do it using Github Actions.

**Comment by 8go** [comment]
@pataquets  Thank you for your idea and suggestion.

How would that work? I have used `docker` but I am not an expert in it. 
And my time is limited, so I do not want to start testing docker images, etc.
And I have not used `Github Actions`. 

Is it just a matter of adding 1 file to the `matrix-commander` repo? 
Would it require maintenance? 
Could you provide the file as a PR? And then test it?

Please advise. Would you be willing to assist me in getting it done?

**Comment by pataquets** [comment]
With the provided Github Actions file and a free [Docker Hub](https://hub.docker.com) account (with the proper infos set on the GA variables) it would be fully automatic on each commit, which would trigger the image build and push from git `master` branch to the Docker Hub image `:latest` tag. More complex branch to tag mappings would require more work, thou.
In short, this would provide sort of a "daily build" feature.

I'm quite tight on time, but if the above is good enough for you atm, I can help with it. Let me know if it works for you and I'll fire a PR.

**Comment by 8go** [comment]
Thank you @pataquets :clap:  :clap:  :clap: 
Very kind of you to contribute. Excellent. The community will hopefully appreciate it. 

I would suggest to make it as simple as possible. No tag-to-branch mapping. The latest commit creates a new version on `Docker Hub`. 

> I'm quite tight on time, 

There is no hurry.  :)

> but if the above is good enough for you atm

Yes it is, the simpler the better. 

> I can help with it.

That would be fantastic! :+1: 

> Let me know if it works for you and I'll fire a PR.

Please do the PR. 

- I assume I have to create the Docker Hub account first ? Correct? 
- What info do I need to pass to you from the Docker Hub account so that you can do the PR (without hurry)?

Final comment: once you have time for the PR, could you please add some new chapter in the README.md file to explain this new docker availability and how to use it, as explained to noobies. :pray: Basically 2 thoughts: a) announce its existence, b) simple explanation for noob users on how to use it. I am sure you will describe it better than me, since docker is not my strong side. Thanks.

**Comment by pataquets** [comment]
> Thank you @pataquets clap clap clap Very kind of you to contribute. Excellent. The community will hopefully appreciate it.
> 
> I would suggest to make it as simple as possible. No tag-to-branch mapping. The latest commit creates a new version on `Docker Hub`.
> 
:+1: This makes everything easier.

> > I'm quite tight on time,
> 
> There is no hurry. :)
> 
:+1:

> > but if the above is good enough for you atm
> 
> Yes it is, the simpler the better.
> 
> > I can help with it.
> 
> That would be fantastic! +1
> 
> > Let me know if it works for you and I'll fire a PR.
> 
> Please do the PR.
> 
>     * I assume I have to create the Docker Hub account first ? Correct?
> 
Yes. It will be needed once the PR is in.

>     * What info do I need to pass to you from the Docker Hub account so that you can do the PR (without hurry)?
> 
To me, nothing. You'll just have to put the credentials secrets in the configuration of the added Action (only visible to you).

> 
> Final comment: once you have time for the PR, could you please add some new chapter in the README.md file to explain this new docker availability and how to use it, as explained to noobies. pray Basically 2 thoughts: a) announce its existence, b) simple explanation for noob users on how to use it. I am sure you will describe it better than me, since docker is not my strong side. Thanks.

Sure! Usage will be not too different from what is now. You'll be able to run it without any previous build step straight away.

**Comment by 8go** [comment]
I will try to get a `Docker Hub` account in the next days.

**Comment by 8go** [comment]
Hi, just to let you know (no time pressure implied):

- I have created a Docker Hub account. 
- I have created an access token for it.
- User name: matrixcommander
- Repository: matrix-commander
- URL: https://hub.docker.com/r/matrixcommander/matrix-commander

I am patiently waiting for your future advice on how to proceed.

**Comment by pataquets** [comment]
@8go: Sent #74.
PyPi status doesn't matter, since Hub's image is always built from source.

**Comment by 8go** [comment]
@pataquets : OK, I didn't not know that. I learned something new. Thanks for explaining.

**Comment by 8go** [comment]
Looking at your Action log it seems it takes around 52 minutes to perform the action. Waiting curiously for outcome :smile:

**Comment by 8go** [comment]
It took exactly 1 hour. Looks like it is working. Thank you again.

I updated the documentation: See commit 4c0822f

Can you @pataquets please :pray: look over these documentation changes in the 2 README files. See if they are accurate and/or if you would like to make any additions/changes.

**Comment by 8go** [comment]
No hurry. 

@pataquets  A question. I auto-generate a file called `versionnumber.txt` (currently hidden through `.gitignore`. 
This file contains just 1 line, the string `2.24.0` (So a 6-byte file.)
Would that help to give it a `tag` for the docker push?

If, when you have time, do you want to make a PR to the a GH action script to use the version number? Just an idea.

**Comment by 8go** [comment]
I am trying it myself, see commit https://github.com/8go/matrix-commander/commit/3325bb88104956fe07cf5ea34b58ac743eb4b68b

Let's see if it works.

**Comment by pataquets** [comment]
Ops! I completely forgot about documenting the DH image. I guess it's 'cause I mostly do it after the image is published and the workflow is settled, which leads me to...
You can pull the version number from git tags, too. Although I'm not that familiar with doing it this way, there should be thousands of recipes out there in Github Actions pulling it of, in case you want to check it. Also, it's a standard practice to always push the latest stable, versioned tag to the `:latest` image tag. In Docker, specifying no tag always implies `:latest` tag.

**Comment by pataquets** [comment]
Docs about Docker Hub image reviewed on #75.

**Comment by pataquets** [comment]
Not having a `:latest`tag results in this when attempting to use the DH's image:
``` console
$ docker run --rm -ti -v ~/tmp/matrix-commander/:/data:z matrixcommander/matrix-commander
Unable to find image 'matrixcommander/matrix-commander:latest' locally
docker: Error response from daemon: manifest for matrixcommander/matrix-commander:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

**Comment by 8go** [comment]
OK, I thought (like in PyPi) DH would just by default serve the last one (by date).

It looks like it requires a `latest` tag. Not very nice.

**Comment by 8go** [comment]
I just read this: 

```
The docker push command does not accept several arguments (if ever one wants to push a selection of several tags (not all) in one go), so one needs to push each tag separately, e.g.:

for t in latest v1.1 dev; do
    docker push "repo:${t}"
done
```

So, we push twice, once with version, a second time with `latest`.

Correct?

**Comment by pataquets** [comment]
Right. You push twice, one with version tag and `:latest` (which will be overwritten, no dupes).
The build & push Github Action accepts multiple tags when pushing.

**Comment by 8go** [comment]
Do you know how to specify it, syntax?

I tried:
``` 
tags:
   - first
   - second
```
It did not like that:

```
tags: first
tags: second
```
Also, he does not like that.

Ideas? if you know, can you make the change?

**Comment by 8go** [comment]
I am trying
```
tags:
    first
    second
```
now. SO far, it did not fail.  :)

**Comment by pataquets** [comment]
Comma-separated. See [docs](https://github.com/docker/build-push-action#customizing).
Also, I think the `--no-sso` command line switch should be recommended in the docs for Docker first run and configuration, since there is no browser (not even an X11 server) in the container and host's OS is not accessible.

**Comment by 8go** [comment]
OK on both. Trying the "comma" solution right now :)

--no-sso : great. Anything else?

**Comment by pataquets** [comment]
:+1: Watch out with running out of free minutes on Github Actions (they have a generous limit, but there is one). With more advanced GA syntax you can run actions on specific events (tag push only, cron-like time, etc), in case you want to refine it later.
I'm still testing, so something might arise, but nothing else, so far.

Expect a PR soon, with an optimized `Dockerfile`.

**Comment by 8go** [comment]
Docker Doc has been updated according to your suggestion.

And thanks for the comments. I am learning from them, so these comments are useful.

**Comment by pataquets** [comment]
Sent PR #76 .
I've noticed that Docker build triggers on any target branch. Since I use GA to build only Dockerfiles, it's usually OK for me, but might not suit you well. Check the docs to restrict build to `master` branch and prevent feature branches to trigger build and pushing to `:latest` tag. Alternatively, other branches could push to their respective branch-named tags for testing.

**Comment by 8go** [comment]
Thank you @pataquets for PR #76. It has been merged. :clap:  :clap:  :clap: 

I have a question: What is the "custom", the standard thing to do: include the tests directory or not? 

It is not too big (1.5MB) and gives users some examples in the test scripts .sh and .py. 

What do you think? Is that something useful?, something that should go into the docker container?

**Comment by pataquets** [comment]
Test files are to be included as long as they're useful and necessary to *build* the software, ie. you want the tests to run and require them to pass for the build to succeed (or to fail otherwise, acting as a build safety net). If the test files are not used at runtime, they're excess weight. Having said that, most of container I've seen, just add the complete source dir and don't care about a few extra kb, even when not needed.
In your case, it is not expected for the users to *read* the test and example files inside the container. They can clone the repo. The built image will be used as a run artifact. *Unless* you expect them to run the tests or some script inside as a troubleshooting tool, when filing bug reports, for instance.

This is, for the most common Docker usage. Maybe some other exotic usages might not fit with the above. I've used Dockerfiles to build software with complex toolchains to later just get the binaries by `cp`'ing them from the built image and run them in my host system, throwing away the image afterwards.

**Comment by 8go** [comment]
OK, we follow the standard then, i.e. we do NOT put the test directory into the container.

**Comment by 8go** [comment]
I close this issue for now. 

If need be re-open it.

**Comment by pataquets** [comment]
Sure, @8go :+1: . Since you have a badge in your Readme's top, you might be interested in the "docker pulls" badge.

**Comment by 8go** [comment]
@pataquets  : good example page where to copy-paste docker-pulls badge from?

**Comment by pataquets** [comment]
> @pataquets  : good example page where to copy-paste docker-pulls badge from?
> 
None that I can remember from the top of my head, but I guess this will do:
https://stackoverflow.com/questions/51515021/how-do-i-show-docker-pulls-as-an-image-in-my-github-readme-file

**Comment by 8go** [comment]
done
