### ISSUE TITLE
Bug: Dockerfile doesn't work anymore and proposed fix

### ISSUE THREAD

**Issue by SamiLehtinen** [8go/matrix-commander#73]
To fix it just change:
COPY [matrix-commander.py](http://matrix-commander.py/) . -> COPY matrix_commander/matrix_[commander.py](http://commander.py/) [matrix-commander.py](http://matrix-commander.py/)
https://github.com/8go/matrix-commander/blob/master/docker/Dockerfile

I'm not saying this is the right way to fix it, but this makes it work. Maybe other steps of the process should be updated instead to match the current Dockerfile?

```
> git diff
diff --git a/docker/Dockerfile b/docker/Dockerfile
index 3b7740d..f4a40dd 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -8,7 +8,7 @@ RUN dnf install -y pip libolm-devel gcc python-devel python3-dbus libffi-devel l
WORKDIR /app

COPY requirements.txt .
-COPY [matrix-commander.py](http://matrix-commander.py/) .
+COPY matrix_commander/matrix_[commander.py](http://commander.py/) [matrix-commander.py](http://matrix-commander.py/)

RUN pip3 install wheel && pip3 install -r /app/requirements.txt
```

**Comment by 8go** [comment]
Thank you @SamiLehtinen 

You are correct, the Dockerfile became outdated. 

There is a new one, see commit [f6d4aa0](https://github.com/8go/matrix-commander/commit/f6d4aa0c119cc71cb6b3f6a2eecc1bbec3cb8359).

Please check it out and report back if that works for you.

See also Issue #70 where @[pataquets](https://github.com/pataquets) offers help to get the `Docker Hub` going.

**Comment by SamiLehtinen** [comment]
Confirmed, the latest version with the Dockerfile update commit is good. Excellent, thank you. https://github.com/8go/matrix-commander/commit/00503dc618212a923aa667b37a8275a16a1c086f

**Comment by 8go** [comment]
Thanks @SamiLehtinen for the confirmation.
