### ISSUE TITLE
Feature request: Git tags for releases

### ISSUE THREAD

**Issue by pacien** [8go/matrix-commander#77]
Would it be possible to add git tags for new releases?

This would help detecting new versions automatically to keep distribution packages up to date (for example https://github.com/NixOS/nixpkgs/pull/176473).

**Comment by 8go** [comment]
@pacien  How is that done correctly? Please advise.

Executing `git tag $(echo VERSION)` before `git commit`? After `git commit` but before `git push` ?

**Comment by pacien** [comment]
Yes, one way is to do as follows:

- Update version number and release notes in `VERSION`, `setup.cfg`, ...
- `git commit -m "release: v$(echo VERSION)"`
- `git tag v$(echo VERSION)`
- `git push && git push v$(echo VERSION)`
- Publish on PyPI, Docker Hub, ...

**Comment by 8go** [comment]
@pacien Thanks for the suggestion. 

I saw that many people add the `v` letter in front of the tag. Seems common. 

Does it matter to you? Better with or without `v`?

The biggest difference between your suggestion and what I did is the pushing of the tag `push origin $(echo VERSION)`. Is that important? Do other people need that? What would other people use that for? To replace the hash with a tag-name in some git commands?

**Comment by 8go** [comment]
I just saw that that extra `push origin $(echo VERSION)` caused the Github Workflow Actions to be fired a second time. Undesired.

Not yet sure how to avoid that.

**Comment by pacien** [comment]
Quoting 8go (2022-06-07 18:52:09)
> I saw that many people add the `v` letter in front of the tag. Seems
> common. Does it matter to you? Better with or without `v`?

This is a popular convention. It's nice to have so that tags for new
releases and other tags are namespaced. Update detection scripts
commonly accept both.

> The biggest difference between your suggestion and what I did is the
> pushing of the tag `push origin $(echo VERSION)`. Is that important?

Oops, I forgot the repository in the commands I wrote previously. You
indeed need to provide the repository when providing a refspec: `git
push origin v$(VERSION)`.

> Do other people need that? What would other people use that for? To
> replace the hash with a tag-name in some git commands?

This is helpful for, amongst other things:
- Automatic release detection. Distributions have scripts periodically
  looking for those tags to alert package maintainers to update their
  packages when there is a new version.
- Easily checking out a given version for debugging, developping or
  when needing a particular version, simply using the tag as a bookmark
  instead of having to scan the whole history to find the latest commit
  with a given version number in a file.
- Build and publishing automation to automatically publish on PyPI,
  Docker Hub and others only when there is a new tagged release.
- Better archiving: GitHub and other platforms can automatically
  generate and keep source and built archives for tags for users to
  download.

Quoting 8go (2022-06-07 19:18:58)
> I just saw that that extra `push origin $(echo VERSION)` caused the
> Github Workflow Actions to be fired a second time. Undesired. Not yet
> sure how to avoid that.

You can either:
- Configure publishing actions to run only for new release tags, or
- Push relevant tags in one command with: `git push --follow-tags`

**Comment by 8go** [comment]
Thanks @pacien for your patience and your detailed response. You might have seen that I already started adding the `v`. Also, I changed the Actions workflow to only trigger on major version upgrades (not on just any push), so that is handled as well. There are already 6 tags now. My workflow seems to be working fine now.

> `git push --follow-tags` :+1:  good tip

Is there a community standard on the tag message? Should it be just short as "release: v2.36.0" to ease bot-parsing, or can it be lengthy like "release: v2.36.0 long explanation of changes ..."?  Does automatic release detection care about the message (`-m` part) of the annotated tag?

**Comment by pacien** [comment]
Quoting 8go (2022-06-10 12:44:12)
> Is there a community standard on the tag message? Should it be just
> short as "release: v2.36.0" to ease bot-parsing, or can it be lengthy
> like "release: v2.36.0 long explanation of changes ..."?  Does
> automatic release detection care about the message (`-m` part) of the
> annotated tag?

None that I'm aware of. The name is often the part that gets scanned
for. The description usually contains just the software name and
version. It can also contain the changelog, but I don't see any benefit
over writing the changelog to a file instead, except perhaps having it
show on GitHub's tag page.

**Comment by 8go** [comment]
OK. Thanks @pacien for sharing your opinion.

**Comment by pataquets** [comment]
@8go : I've noticed a few details in the tagging/versioning and releasing on the Docker side. I'll drop them here, since they're related with the issue at hand.
* Releasing/pushing only X.0 versions to Docker Hub feels strange. What happens with bugfix (ie. minor) releases? they should be pushed, too, IMO.
* Docker Hub image publishing can use only git tags, making the `VERSION` file unnecessary.
* If using git tags, a richer image tagging can be implemented, eg v1.2.3 would be accessible under `:1`, `:1.2` and `:1.2.3` tags. Later, when 1.2.4 gets published, `:1` and `:1.2` would mean the newly pushed `:1.2.4`. This is a common best practice for versioning Docker images.

I can provide the above tag-based image versioning in a PR, if you feel like it.

**Comment by 8go** [comment]
Thank you @pataquets for your helpful input. :+1: 

Thanks for making the package better.

> Releasing/pushing only X.0 versions to Docker Hub feels strange. 

Please see PR #84 and its comments. v3.0.1 was a mistake on my side. Anyway, I think this is fixed. Looking at the PR #84 do you agree?

> `VERSION` file is unnecessary.

But it is not harmful either, right? My local workflow currently uses it. So, there is no harm in having it around, correct?

> If using git tags, a richer image tagging can be implemented, eg v1.2.3 ...

I might not understand something correctly. Help me out. This is what I currently have:

```
$ git tag --list -n --sort=-refname # list tags
v3.0.1          release: v3.0.1
v3.0.0          release: v3.0.0
v2.38.1         release: v2.38.1
v2.38.0         release: v2.38.0
v2.37.7         release: v2.37.7
v2.37.6         release: v2.37.6
v2.37.5         release: v2.37.5
v2.37.4         release: v2.37.4
v2.37.3         release: v2.37.3
v2.37.2         release: v2.37.2
v2.37.1         release: v2.37.1
v2.37.0         release: v2.37.0
v2.36.0         release: v2.36.0
v2.35.0         added feature --delete-device to delete devices
v2.34.1         added better macOS M1 install instructions
v2.34.0         added feature --get-openid-token
v2.33.1         added 3 logos to top of README file
v2.33.0         added features --export-keys and --import-keys
```

```
$git tag --list -n20 $(git describe) # details of last tag
v3.0.1          release: v3.0.1
    
    added feature --logout to logout and remove device from use
    
    - also invalidates the corresponding access-token
    
    - allows use cases like `ghost`
    
    - `ghost`: `matrix-commander` can be used in an ephemeral fashion, in a
       fire-and-forget style. A single batch command can log in, create a
       new device, send a message, and then log out and delete the device.
    
           --logout LOGOUT       Logout this or all devices from the Matrix homeserver.
                             This requires exactly one argument. Two choices are
                             offered: 'me' and 'all'. Provide one of these choices.
                             If you choose 'me', only the one device matrix-
                             commander is currently using will be logged out. If
                             you choose 'all', all devices of the user used by
                             matrix-commander will be logged out. While --logout
```

Is this different to what you suggest? Please explain.

> I can provide the above tag-based image versioning in a PR, if you feel like it.

Certainly all PRs are welcome. But I don't yet know what I am doing incorrectly.

**Comment by pataquets** [comment]
> Thank you @pataquets for your helpful input. +1
> 
> Thanks for making the package better.
> 
Don't mention it. Happy to help and thanks to you for sharing this software :wink:

> > Releasing/pushing only X.0 versions to Docker Hub feels strange.
> 
> Please see PR #84 and its comments. v3.0.1 was a mistake on my side. Anyway, I think this is fixed. Looking at the PR #84 do you agree?
> 

Oh, I see. Looks like that PR solved it. Just notice that now the image build will be triggered *only* on new tags (not branches, nor PRs). Anyway, `:latest` will mean latest *stable* (ie. tagged) version, which is expected. However, no `:master` image tag for the latest `HEAD` code, but it can be worked around by `docker build`ing using the repo URI. No complaint, just for completeness sake.

> > `VERSION` file is unnecessary.
> 
> But it is not harmful either, right? My local workflow currently uses it. So, there is no harm in having it around, correct?
> 

I wasn't aware of it being necessary elsewhere. In fact, no harm. The only problem might be if tags and file get out of sync, but that's another story.

> > If using git tags, a richer image tagging can be implemented, eg v1.2.3 ...
> 
> I might not understand something correctly. Help me out. This is what I currently have:
> 
> [snipped]
> 
> Is this different to what you suggest? Please explain.
> 

Oh, I was talking about the SemVer image tagging provided by the [Docker metadata Github Action](https://github.com/marketplace/actions/docker-metadata-action), which is currently not implemented on your workflow. That would get that image tagging scheme, as done commonly for public images (see [Python official Docker image](https://hub.docker.com/_/python) as example). You would keep `:x.y.z`image tags for all released versions, but `:x` and `:x.y` would be a moving target pointing to corresponding latest version, mostly used for pinning to specific major or major.minor version (think Python).
Unfortunately I cannot commit more time atm to implement this myself, but you might take my latest merged PRs to see it, if you feel like it (there have been a handful of them, lately).

> > I can provide the above tag-based image versioning in a PR, if you feel like it.
> 
> Certainly all PRs are welcome. But I don't yet know what I am doing incorrectly.

So, as far as Docker image publishing is concerned, it's all OK, specially after the above mentioned PR.

**Comment by 8go** [comment]
I think now I get it. The idea is to add 2 new tags `:x` and `:x.y` and they (sort of like soft-links) point to some existing release, e.g. the latest/highest of  `:x.y.z`.

If I understand correctly, this should be done locally (github) and as well on `dockerhub`. 

OK, in the future I might look into this. Thanks @pataquets

**Comment by pataquets** [comment]
That's it, sort of soft-links. Notice that you just `git tag x.y.z`, as always (no extra steps required on the git side) . The mentioned Github Action step figures out the `:x`, `:x.y` image tags and, as it pushes the `:x.y.z` image, it also pushes the same image to `:x` and `:x.y`.

**Comment by 8go** [comment]
If someone understand [Docker metadata Github Action](https://github.com/marketplace/actions/docker-metadata-action) well, please provide a tested PR that auto-generates the `:x` and `:x.y` tags and images. :please: Thanks. I will not tackle that.

**Comment by pataquets** [comment]
@8go: check out #99 :wink:

**Comment by 8go** [comment]
Loving PR #99 
Thank you :+1:  for your time. Greatly appreciated!

**Comment by 8go** [comment]
Thank you @pataquets for this nice PR ! Worked like a charm. 

DockerHub has now version `latest`, `3`, `3.5` and `3.5.4`.  All pointing to the dame docker image! Excellent.

:clap: :clap: :clap:  :heart: 

Closing issue. If anything is missing, something new comes up, please comment here and open issue again!

**Comment by pacien** [comment]
Quoting 8go (2022-06-07 18:52:09)
> I saw that many people add the `v` letter in front of the tag. Seems
> common. Does it matter to you? Better with or without `v`?

This is a popular convention. It's nice to have so that tags for new
releases and other tags are namespaced. Update detection scripts
commonly accept both.

> The biggest difference between your suggestion and what I did is the
> pushing of the tag `push origin $(echo VERSION)`. Is that important?

Oops, I forgot the repository in the commands I wrote previously. You
indeed need to provide the repository when providing a refspec: `git
push origin v$(VERSION)`.

> Do other people need that? What would other people use that for? To
> replace the hash with a tag-name in some git commands?

This is helpful for, amongst other things:
- Automatic release detection. Distributions have scripts periodically
  looking for those tags to alert package maintainers to update their
  packages when there is a new version.
- Easily checking out a given version for debugging, developping or
  when needing a particular version, simply using the tag as a bookmark
  instead of having to scan the whole history to find the latest commit
  with a given version number in a file.
- Build and publishing automation to automatically publish on PyPI,
  Docker Hub and others only when there is a new tagged release.
- Better archiving: GitHub and other platforms can automatically
  generate and keep source and built archives for tags for users to
  download.

Quoting 8go (2022-06-07 19:18:58)
> I just saw that that extra `push origin $(echo VERSION)` caused the
> Github Workflow Actions to be fired a second time. Undesired. Not yet
> sure how to avoid that.

You can either:
- Configure publishing actions to run only for new release tags, or
- Push relevant tags in one command with: `git push --follow-tags`

**Comment by pacien** [comment]
Quoting 8go (2022-10-11 10:23:38)
> @pacien : Is there anything broken? Is it not working well as is?

(Please ignore the previous message. GitHub suddenly decided to repost
my old messages again. Probably an issue with their email system…)
