### ISSUE TITLE
Feature request: Use `XDG_*` environment variables for data path

### ISSUE THREAD

**Issue by pacien** [8go/matrix-commander#78]
Currently, configuration files and store data are put under the user's home
directory in `~/.config` and `~/.local`. The [XDG Base dir specification]
describes `$XDG_CONFIG_HOME` and `$XDG_DATA_HOME` for those. It would be more
flexible to use the values of those environment variables when they are
defined.

[XDG Base dir specification]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

**Comment by 8go** [comment]
Thank you @pacien 

Good idea. I agree. 

Do you feel like making a PR for this? :pray:

**Comment by 8go** [comment]
@pacien  Done. See commit [4447f09](https://github.com/8go/matrix-commander/commit/4447f0967d982ab4cbd618164595d565c7b239ce)

**Comment by 8go** [comment]
See commit 61737bd and version v.2.37.6

I switched from PyPi package `xdg` to `pyxdg`

- incompatibility: new dependency `pyxdg`. Please install `pyxdg` if necessary.
- switched from https://pypi.org/project/xdg/ v5.1.1
  to https://pypi.org/project/pyxdg/ v0.28

```
     - python3 package pyxdg must be installed to support `XDG_*` env vars.
       Be careful. Multiple packages install in the same directory `xdg` and
       overwrite each other. These packages can be conflicting. Specifically,
       packages `pyxdg` and `xdg` collide. If you already have `xdg` installed
       you cannot just simply install `pyxdg`; in this case you should opt
       for a separate Python environment.
       - pip3 uninstall --user xdg
       - pip3 install --user --upgrade pyxdg
```

**Comment by 8go** [comment]
PyPi updated in pull request [7302b20](https://github.com/8go/matrix-commander/commit/7302b20d53bd821b60d80c346fb3a8f013648044)
