### ISSUE TITLE
XDG python libs not automatically installed when installing through pip

### ISSUE THREAD

**Issue by crazyminecuber** [8go/matrix-commander#85]
I had to pip install xdg and pyxdg to get it working. Should probably be added to some requirements.txt somewhere.

**Comment by 8go** [comment]
Thank you @crazyminecuber 

Your input is appreciated.

However, `pyxdg` already is in the `requirements.txt` file.

And `xdg` should *not* be used. 

Did you run `pip install -r requirements.txt` to automatically install all required Python packages? Everything should have worked. I cannot find a problem.

Same for a plain `pip` installation. `pip` should automatically install pyxdg unless there is a conflict on your side.

Please try again, remove `xdg`, `pyxdg` and `matrix-commander` and re-install `matrix-commander` via `pip` and report back if there really is an issue. To me all looks well and `pyxdg` gets installed automatically. 

Which platform? OS?

**Comment by 8go** [comment]
See also comments in Issue #78

**Comment by crazyminecuber** [comment]
Sorry, I just thought that you could specify dependencies in pip like you can in a normal package manager so that the end user does not have to think of manually installing other pip packages. Then it is probably nothing wrong except my patience at reading long and detailed readme:s :)

**Comment by 8go** [comment]
`pip` does support dependencies. And `matrix-commander` specified them so that `pip` automatically installs all dependencies. Maybe you had a dependency conflict and hence `pip` skipped the automatic `pyxdg` installation. 

Anyway, have fun using `matrix-commander`. :+1:

**Comment by 8go** [comment]
@crazyminecuber You were right! The PyPi build chain was in deed missing the `pyxdg` dependency. 

Fixed now!  Thank you for finding it and pointing it out.
