### ISSUE TITLE
Question: Creating multiple users

### ISSUE THREAD

**Issue by lunarindustrial** [8go/matrix-commander#86]
I did: 

matrix-commander --login password

and created the first user credentials.json file.

I need to be able to login as multiple users, and create their own credentials files.

matrix-commander --login password --user-login

doesn't go anywhere to create a new credentials file for another user.

What is the right syntax for creating a credentials files for another user?

**Comment by edwinsage** [comment]
I don't have the ability to test this right now, but after logging in the first time, you can move the created `credentials.json` file and `store/` directory to a different location (maybe a subdirectory for the username).  Then run again with `--login` and do the same again with a different subdirectory.  Then when you want to run as user A, run MC with `--credentials user_a/credentials.json` and `--store user_a/store`.

**Comment by 8go** [comment]
Thank you @edwinsage 

@lunarindustrial :  @edwinsage is correct. The credentials file only holds one single user. To handle multiple users, one has to create and use multiple credentials files. Follow @edwinsage suggestions, it is the correct solution.

**Comment by lunarindustrial** [comment]
OK, thank you for taking the time to look at this, and come up with a solution.  Apologies for getting back late.  I will try it as you suggested.  The matrix server is running very smoothly now, I'm looking forward to doing a little automation with your tool.
