### ISSUE TITLE
Enhancement: flag to enable JSON output to stdout (basic work started)

### ISSUE THREAD

**Issue by HoboDev** [8go/matrix-commander#94]
I have started a basic implementation of ```--output-json```
to get JSON on stdout, so I don't have to deconstruct the message lines.

You can check it out here:
https://github.com/HoboDev/matrix-commander/tree/feat-output-json

It is lacking a bit on documentation and maybe does not adhere too much to existing variable names.
But at least it's a start. So far I've covered basic messages and media files.

**Comment by 8go** [comment]
Hi @HoboDev 

I want to centralize the discussion in ONE issue, in Issue #92. I am moving your comments over to Issue #92 and will then close this issue. For any follow up use Issue #92
