### ISSUE TITLE
Question: How would I go about saving the output from --joined-rooms and/or --joined-members to json format?

### ISSUE THREAD

**Issue by tacticalgeek** [8go/matrix-commander#95]
Hello, how do I save the out thats in my terminal to a json file? Or any file file for that matter please.

**Comment by 8go** [comment]
You can use output redirect (`>` in Linux) to write any and all output to a file. 

E.g. `matrix-commander ... arguments ... > myoutput.txt` will write it to a text file. 

You want a JSON file? Take the text file and convert it with JSON tools and/or a script to your desired JSON format.

**Comment by 8go** [comment]
This could also be related to Issue #92 and the general output-as-JSON discussion. 

Maybe in the context of tackling Issue #92 something can be done about --joined-rooms and/or --joined-members as well.

**Comment by 8go** [comment]
Hi @tacticalgeek 

Check out commit [e09a4f1](https://github.com/8go/matrix-commander/commit/e09a4f15ede27aff7a4a2b47d487b9a85c0ad44b)

Test it and give your feedback?

If all happy then please close this issue. Any other JSON/raw data/etc comments please on the Issue #92 

I want to centralize all discussion in one place, in Issue #92 .
